/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_menuglobale (void);
GtkWidget* create_menu_reclam (void);
GtkWidget* create_ajout_reclam (void);
GtkWidget* create_afficher_reclam (void);
GtkWidget* create_recherche_reclam (void);
GtkWidget* create_recherche2_reclam (void);
GtkWidget* create_modif_reclam (void);
GtkWidget* create_plusreclam_reclam (void);
GtkWidget* create_noter_reclam (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_interface_capteur (void);
GtkWidget* create_ahmed_supprimer (void);
GtkWidget* create_ahmed_modifier (void);
GtkWidget* create_ahmed_captdef (void);
GtkWidget* create_gestion_stock (void);
GtkWidget* create_fiche_stock (void);
GtkWidget* create_modifier_stock (void);
GtkWidget* create_recherche_stock (void);
